# Generated by Django 2.2.7 on 2019-11-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auctions',
            field=models.ManyToManyField(null=True, to='auctions.Auction'),
        ),
    ]
