# Generated by Django 2.2.7 on 2019-11-13 22:13

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_profile_auctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bid_on',
            field=models.ManyToManyField(to='auctions.Item'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=stdimage.models.JPEGField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='auctions',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.JPEGField(blank=True, upload_to='images/'),
        ),
    ]
