# Generated by Django 2.2.7 on 2019-11-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20191113_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='items_won',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bid_on',
            field=models.ManyToManyField(related_name='bidders', to='auctions.Item'),
        ),
    ]
