# Generated by Django 2.2.7 on 2019-11-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20191113_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
