# Generated by Django 2.2.7 on 2019-11-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_item_picked_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
    ]
