# Generated by Django 2.2.7 on 2019-11-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug',
            field=models.SlugField(default=123456789),
            preserve_default=False,
        ),
    ]
