# Generated by Django 2.2.7 on 2019-11-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Auction code'),
        ),
    ]
